
api-version: 2019-12-01
location: uksouth
name: spook-the-midlands
properties:
  containers:
  - name: streamlitapp
    properties:
      image: spookyface.azurecr.io/spook-midlands:v1
      ports:
      - port: 80
        protocol: TCP
      - port: 443
        protocol: TCP
      resources:
        requests:
          cpu: 2.0
          memoryInGB: 1.5
  imageRegistryCredentials:
  - server: spookyface.azurecr.io
    username: spookyface
    password: gj04/oGtdpN3mqIyCG6VuVYeTbc3EFdS
  restartPolicy: Never
  ipAddress:
    ports:
    - port: 443
      protocol: TCP
    - port: 80
      protocol: TCP
    type: Public
    dnsNameLabel: spookthemidlands
  osType: Linux
tags: null
type: Microsoft.ContainerInstance/containerGroups